fix: remove hwsim dependency for avoiding conflict
An error appeared when using OpenWrt 25.12 BuildRoot and selecting
vwifi package:

Installing vwifi (7.0-r1)
ERROR: vwifi-7.0-r1: trying to overwrite etc/modules.d/mac80211-hwsim owned by kmod-mac80211-hwsim-6.12.103.6.18.39-r1.

So it seems that vwifi is currently shipping its own version of a file
also provided by the kmod-mac80211-hwsim package.